In [1]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

import numpy as np
null_vector=np.zeros(10)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
# 2. Create a vector with values ranging from 10 to 49.

import numpy as np
new_vector=np.arange(10,50)
print(new_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np
matrix_3=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(matrix_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

import numpy as np
l=[1,2,0,0,4,0]
final_list=np.nonzero(l)
print('Indices of non-zero elements :')
print(final_list)

Indices of non-zero elements :
(array([0, 1, 4], dtype=int64),)


In [5]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np
array=np.random.randint(low=1,high=100,size=(10,10))
print('The 10x10 array with random values is :\n')
print(array)
print('\n The minimum value in the array is :',np.min(array))
print('The maximum value in the array is :',np.max(array))

The 10x10 array with random values is :

[[65 64 96 22  5 12 41  3 18 12]
 [76 15 17  5  5 88 32 99 20 67]
 [28 63 53 18 54 65 71 59 64 68]
 [90 71 29 48 79 20 78 79 99 17]
 [ 9 13  7 94 42 64 41 35 25  3]
 [78 11 46 34 34 89 27 53 21 22]
 [87 96 40 92 16 40 95 89 39 36]
 [31 13 30  5 67 53  2 70 14 82]
 [64  7 37 67 62 60 95 32 65 78]
 [89 31 13 45 51 33 32  3 45 34]]

 The minimum value in the array is : 2
The maximum value in the array is : 99


In [8]:
# 6. Create a random vector of size 30 and find the mean value.

import numpy as np
random_vector=np.random.randint(1,100,30)
mean_value=np.mean(random_vector)
print('Random Vector is :', random_vector)
print('Mean value of the vector is :', mean_value) 

Random Vector is : [90 16 23 50 12 59 40 52 61 25 86 85 18 22 82 84 59  6 92  1 11 12 11 73
 30 29 96 49 69  7]
Mean value of the vector is : 45.0
